# -*- coding: utf-8 -*-
"""WorldLargestBanks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10E8wvokYcBwP3hyv8_4vnKiZQcEh7izA

# Imports
"""

import logging
import pandas as pd
import requests
import sqlite3
from bs4 import BeautifulSoup
import plotly.express as px
import plotly.graph_objects as go

logging.basicConfig(
    filename="code_log.txt",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)

from extract_methods import extract_exchange_rates_from_csv, extract_tables_from_web
from transform_methods import transform_data
from load_methods import load_to_csv, load_to_sql, verify_sql_data

WEB_URL = "https://web.archive.org/web/20230908091635 /https://en.wikipedia.org/wiki/List_of_largest_banks"
# By market capitalization, By total assets, Banks by country or territory

CSV_FILE = "Exchange Rate.csv"

SQLITE_DB = "Largest_banks_data.sql"
OUT_CSV_FILE = "Largest_banks_data.csv"

if __name__ == "__main__":
    table_str = extract_tables_from_web(WEB_URL)
    change_rates_df = extract_exchange_rates_from_csv(CSV_FILE)
    dataframe = transform_data(table_str, change_rates_df)

    load_to_csv(OUT_CSV_FILE, dataframe)
    load_to_sql(SQLITE_DB, dataframe)

    verify_sql_data(SQLITE_DB)
