"""CountriesByGDP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwLCYVCdcDwLtAKF3UkiPzIOG6ABOuSe

# Imports
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import sqlite3


"""# Extract Methods"""

def extract_tables_from_web(url):
  res = requests.get(url)

  soup = BeautifulSoup(res.content, 'html.parser')

  tables = soup.find_all('table')
  print(f"found {len(tables)} tables")

  return tables

#-------- OR -------#
# dfs = pd.read_html(str(soup))

# print(f"pandas found {len(dfs)} tables")

# dfs[2].head()