"""CountriesByGDP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwLCYVCdcDwLtAKF3UkiPzIOG6ABOuSe

# Imports
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import sqlite3

"""# Load Methods"""

SQLITE_PATH = './sqlite.db'
SQLITE_TABLE_NAME = 'GDP_FOR_COUNTRIES'

EXCEL_PATH = './data.csv'

def load_to_formats(dataframe, formats):
  for format in formats:
    if format == 'csv':
      dataframe.to_csv(EXCEL_PATH)

    if format == 'database':
      connection = sqlite3.connect(SQLITE_PATH)

      dataframe.to_sql(name=SQLITE_TABLE_NAME, con=connection, if_exists='replace', index=False)
