# -*- coding: utf-8 -*-
"""CountriesByGDP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwLCYVCdcDwLtAKF3UkiPzIOG6ABOuSe

# Imports
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import sqlite3

from extract_methods import extract_tables_from_web
from transform_methods import transform_table_data
from load_methods import load_to_formats

"""# ETL Main Section"""

if __name__ == "__main__":
  tables = extract_tables_from_web('https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29')
  dataframe = transform_table_data(tables)
  load_to_formats(dataframe, ["csv", "database"])
